schedules:
 - cron: '0 19 * * Mon,Tue,Wed,Thu,Fri'
   displayName: Daily release
   branches:
    include:
      - main
   always: true 


trigger: none

name: $(Build.DefinitionName)_$(date:yyyyMMdd)$(Rev:.r)

variables:
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: 'svc-conn-daily-development-rg'
  resourceGroupNameDev: 'daily-development'
  bicepFile: './main.bicep'
  bicepParamFileDev: './parameters/main-dev.bicepparam'
  deploymentName: $[replace(variables['Build.BuildNumber'], ' ', '_')]


pool:
  vmImage: $(vmImageName)

stages:

 - stage: CheckoutAndMoveFiles
   jobs:
    - job: CheckoutCode
      displayName: Checking out bicep files
      steps:

      - checkout: self
        persistCredentials: true  # Persist the credentials for subsequent steps

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(System.DefaultWorkingDirectory)'
          artifactName: BicepTemplates

 - stage: DeployDev
   jobs:
    - deployment: 
      environment: 'Dev'
      displayName: Deployment Dev
      strategy:
       runOnce:
        deploy:
          steps:
            - script: echo "Deploying the project with name $(deploymentName)"
            - checkout: none #skip checking out the default repository resource
            - task: DownloadBuildArtifacts@0
              displayName: 'Download Build Artifacts'
              inputs:
                artifactName: BicepTemplates
                downloadPath: $(Build.ArtifactStagingDirectory)

            - task: AzureCLI@2
              inputs:
                azureSubscription: $(azureServiceConnection)
                scriptType: bash
                scriptLocation: inlineScript
                useGlobalConfig: true
                inlineScript: |
                  az --version
                  az deployment group create \
                    --resource-group $(resourceGroupNameDev) \
                    --parameters $(Build.ArtifactStagingDirectory)/BicepTemplates/$(bicepParamFileDev) \
                    --name '$(deploymentName)'

 